version: "3"

services:
  redis:
    container_name: redis-message-orchestrator
    image: redis
    command: redis-server
    ports:
      - "6379:6379"
  zookeeper:
    container_name: zookeeper-message-orchestrator
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
  kafka:
    container_name: kafka-message-orchestrator
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "message:1:1"
    depends_on:
      - zookeeper
  kafka-ui:
    container_name: kafka-ui-message-orchestrator
    image: provectuslabs/kafka-ui
    hostname: kafka-ui
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - zookeeper
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: localhost:2181