### SERVER ###
server:
  port: ${SERVER_PORT:4000}

### SPRING ###
spring:
  output:
    ansi:
      enabled: ALWAYS
  redis:
    database: ${redis.database}
    host: ${redis.host:localhost}
    port: ${redis.port:6379}
  kafka:
    config:
      topic:
        partitions: ${kafka.topic.default.partitions:3}
        replicas: ${kafka.topic.default.replicas:3}
    bootstrapServers: ${KAFKA_SERVERS}

### LOG ###
logging:
  level:
    root: INFO
    com:
      example: TRACE

### ACTUATOR ###
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'